In [ ]:
import numpy as np
import math as m
np.set_printoptions(precision=4)
np.set_printoptions(suppress=True)

#input
k = -2.3
n = 2.5

a = np.array([[3+k, 1.7+n, 1.6+2*k, 5.5-n],
              [1.7+n, 1, 2.5-k, 4.3+n],
              [1.6+2*k, 2.5-k, 3, 2.7-k],
              [5.5-n, 4.3+n, 2.7-k, 4.8+n]])

j = np.array([[1, 0, 0, 0],
              [0, 1, 0, 0],
              [0, 0, 1, 0],
              [0, 0, 0, 1]])

accuracy = 10**-4

def qr(a):
    
    i = 1
    delta = 1
    
    while(delta > accuracy):

        s1 = m.sqrt(a[0][0]**2 + a[1][0]**2 + a[2][0]**2 + a[3][0]**2)
        print(s1)
        print(a[0][0])
        mu1 = (2*s1*(s1-a[0][0]))**(-1/2)
        w1 = np.dot(mu1, [a[0][0]-s1, a[1][0], a[2][0], a[3][0]])
        a1 = (j - 2*w1*np.vstack(w1)).dot(a)

        s2 = m.sqrt(a1[1][1]**2 + a1[2][1]**2 + a1[3][1]**2)
        mu2 = (2*s2*(s2-a1[1][1]))**(-1/2)
        w2 = np.dot(mu2, [0, a1[1][1] - s2, a1[2][1], a1[3][1]])
        a2 = (j - 2*w2*np.vstack(w2)).dot(a1)        

        s3 = m.sqrt(a2[2][2]**2 + a2[3][2]**2)
        mu3 = (2*s3*(s3-a2[2][2]))**(-1/2)
        w3 = np.dot(mu3, [0, 0, a2[2][2] - s3, a2[3][2]])
        a3 = (j - 2*w3*np.vstack(w3)).dot(a2)      

        r = a3
        q = ((j - 2*w1*np.vstack(w1)).dot((j - 2*w2*np.vstack(w2)))).dot((j - 2*w3*np.vstack(w3)))

        an = r.dot(q)
        #delta matrix
        dm = abs(a - an)
        
        delta = np.array([dm[0][0], dm[1][1], dm[2][2], dm[3][3]]).max()
        
        print("Iteration ", i)
        if (i==1):
            print("a1 =\n", a1)
            print("a2 =\n", a2)
            print("a3 =\n", a3)
        print("Q =\n", q)
        print("R =\n", r)
        print("A =\n", an)
        print("delta = %.5f" % delta)
        print("---------------------------------------")

        a = an
        i += 1
        
    print("Answer:")  
    print("%.4f, %.4f, %.4f, %.4f" % (a[0][0], a[1][1], a[2][2], a[3][3]))

In [20]:
print("A =\n", a)
print("---------------------------------------")
qr(a)

A =
 [[ 0.7  4.2 -3.   3. ]
 [ 4.2  1.   4.8  6.8]
 [-3.   4.8  3.   5. ]
 [ 3.   6.8  5.   7.3]]
---------------------------------------
6.010823570859487
0.7000000000000002
Iteration  1
a1 =
 [[ 6.0108  2.1861  4.0028  6.2487]
 [-0.      2.5927 -0.7381  4.2308]
 [ 0.      3.6624  6.9558  6.8352]
 [-0.      7.9376  1.0442  5.4648]]
a2 =
 [[ 6.0108  2.1861  4.0028  6.2487]
 [-0.      9.1182  3.493   8.7057]
 [ 0.     -0.      4.5811  4.3237]
 [-0.     -0.     -4.1024  0.0215]]
a3 =
 [[ 6.0108  2.1861  4.0028  6.2487]
 [-0.      9.1182  3.493   8.7057]
 [ 0.     -0.      6.1495  3.2066]
 [ 0.      0.      0.     -2.9004]]
Q =
 [[ 0.1165  0.4327 -0.8094 -0.3795]
 [ 0.6987 -0.0578  0.3586 -0.6163]
 [-0.4991  0.6461  0.4457 -0.3672]
 [ 0.4991  0.6261  0.1326  0.5842]]
R =
 [[ 6.0108  2.1861  4.0028  6.2487]
 [-0.      9.1182  3.493   8.7057]
 [ 0.     -0.      6.1495  3.2066]
 [ 0.      0.      0.     -2.9004]]
A =
 [[ 3.3484  8.9729 -1.4688 -1.4476]
 [ 8.9729  7.1799  5.9807 -1.816 ]
 [-1