In [49]:
import numpy as np

#     input
p1 = 20.60374
p2 = -96.01179
p3 = -7.15265

m2 = [[1, 0, 0],
      [-0.1111, 0.3704, -4.6667],
      [0, 0, 1]]

m1 = [[0.108, -1.6019, 2.2419],
      [0, 1, 0],
      [0, 0, 1]]

a = 0
b = 1
   
def solve(l):
    return l**3 - p1 * l**2 - p2 * l - p3

    
while (True):
    f1 = solve(a)
    f2 = solve(b)

    if ((f1>0 and f2<0) or (f1<0 and f2>0)):
        break
    else: 
        a += 1
        b += 1

print('[%d ; %d]' % (a, b))


while (b-a>0.001):
    ab = (a+b)/2
    f1 = solve(a)
    f2 = solve(ab)
    f3 = solve(b)

    if ((f1>0 and f2<0) or (f1<0 and f2>0)):
        b = ab
    elif ((f3>0 and f2<0) or (f3<0 and f2>0)):
        a = ab

    print('f (%f) = %f ; [%f ; %f]' % (ab, f2, a, b))

lamb = (a+b)/2

y = np.array([[lamb**2], [lamb], [1]])
m1 = np.array(m1)
m2 = np.array(m2)


print('\n lambda = ', lamb)
print('\n y = \n', y)
print('\n M1 = \n', m1)
print('\n M2 = \n', m2)
print('\n M2*M1*y = \n', m2.dot(m1).dot(y))

[7 ; 8]
f (7.500000) = -9.844300 ; [7.000000 ; 7.500000]
f (7.250000) = 1.332169 ; [7.250000 ; 7.500000]
f (7.375000) = -4.279835 ; [7.250000 ; 7.375000]
f (7.312500) = -1.479043 ; [7.250000 ; 7.312500]
f (7.281250) = -0.074648 ; [7.250000 ; 7.281250]
f (7.265625) = 0.628469 ; [7.265625 ; 7.281250]
f (7.273438) = 0.276836 ; [7.273438 ; 7.281250]
f (7.277344) = 0.101075 ; [7.277344 ; 7.281250]
f (7.279297) = 0.013209 ; [7.279297 ; 7.281250]
f (7.280273) = -0.030721 ; [7.279297 ; 7.280273]

 lambda =  7.27978515625

 y = 
 [[52.99527192]
 [ 7.27978516]
 [ 1.        ]]

 M1 = 
 [[ 0.108  -1.6019  2.2419]
 [ 0.      1.      0.    ]
 [ 0.      0.      1.    ]]

 M2 = 
 [[ 1.      0.      0.    ]
 [-0.1111  0.3704 -4.6667]
 [ 0.      0.      1.    ]]

 M2*M1*y = 
 [[-3.69609847]
 [-1.55963104]
 [ 1.        ]]
